$$
\begin{array}{c}
\LARGE \textbf{Trabajo\ Final\ de\ Comunicaciones\ Digitales}
\end{array}
$$

$$
\begin{aligned}
&\textbf{Introducción}
\end{aligned}
$$

$$
\begin{aligned}
&\textbf{Marco teórico}
\end{aligned}
$$

$$
\begin{aligned}
&\text{El auge del Internet de las Cosas (IoT) ha impulsado el desarrollo de tecnologías de comunicación de bajo consumo y largo alcance,} \\
&\text{conocidas como Low Power Wide Area Networks (LPWAN). Dentro de este marco, LoRa (Long Range) es el estándar que se ha consolidado} \\
&\text{como una tecnología ideal para la comunicación inalámbrica de largo alcance y bajo consumo energético.} \\[1em]
&\text{En este sentido, el artículo propuesto por la cátedra introduce una formulación matemática para la modulación LoRa, la cual puede} \\
&\text{describirse como una modulación chirp con desplazamiento de frecuencia (Frequency Shift Chirp Modulation, FSCM).Esta técnica se basa} \\
&\text{en la codificación de bits en símbolos enteros y en la generación de señales chirp cuya frecuencia depende de dichos símbolos. Además,} \\
&\text{en esta formulación, la información está codificada en el desplazamiento inicial de frecuencia del chirp, y no depende de la pendiente} \\
&\text{ni en la duración de la señal. Este enfoque permite definir una base ortogonal de señales discretas, lo que favorece una demodulación} \\
&\text{eficiente mediante la Transformada Rápida de Fourier (FFT).}
\end{aligned}
$$

$$
\begin{aligned}
&\textbf{Desarrollo}
\end{aligned}
$$

$$
\begin{aligned}
&\text{Este proceso de codificación, tal como se describe matemáticamente en el artículo, puede descomponerse en varias etapas fundamentales.} \\
&\text{La primera de ellas es el mapeo de bits a un símbolo decimal, y comienza con un vector } w(nT_s) \text{ compuesto por una cantidad fija de bits} \\
&\text{determinada por el parámetro Spreading Factor (SF), el cual representa la cantidad de bits por símbolo y se define como:} \\[1em]
&\hspace{8cm} SF = \log_2(M) \\[1em]
&\text{Donde $M$ es la cantidad total de símbolos posibles (cardinalidad de la modulación). Por ejemplo, si $SF = 5$, existen $2^5 = 32$ símbolos distintos.} \\
&\text{El valor decimal resultante de este mapeo, denotado como $s(nT_s)$, se obtiene al sumar los valores ponderados de los bits del vector $w(nT_s)$.} \\
&\text{Este número representa directamente la frecuencia inicial desde la cual se genera la señal chirp para su transmisión.} \\[1em]
&\textbf{Fórmula de codificación:} \\[1em]
&\hspace{8cm} s(nT_s) = \sum_{h=0}^{SF-1} w_h(nT_s) \cdot 2^h \quad (1) \\[1em]
&\text{donde:} \\
&\hspace{1cm} s(nT_s) \in \{0, ..., 2^{SF} - 1\} \text{ es el símbolo codificado} \\
&\hspace{1cm} w_h(nT_s) \in \{0, 1\} \text{ son los bits del bloque actual, ordenados desde el LSB} \\
&\hspace{1cm} SF \text{ es el Spreading Factor (cantidad de bits por símbolo)} \\
&\hspace{1cm} h \text{ es el índice del bit dentro del bloque}
\end{aligned}
$$

$$
\begin{aligned}
&\text{Este proceso de codificación, tal como se describe matemáticamente en el artículo, puede descomponerse en varias etapas fundamentales.} \\
&\text{La primera de ellas es el mapeo de bits a un símbolo decimal, y comienza con un vector $w(nT_s)$ compuesto por una cantidad fija de bits} \\
&\text{determinada por el parámetro Spreading Factor (SF), el cual representa la cantidad de bits por símbolo y se define como:} \\[1em]
&\hspace{8cm} SF = \log_2(M) \\[1em]
&\text{Donde $M$ es la cantidad total de símbolos posibles (cardinalidad de la modulación). Por ejemplo, si $SF = 5$, existen $2^5 = 32$ símbolos distintos.} \\
&\text{El valor decimal resultante de este mapeo, denotado como $s(nT_s)$, se obtiene al sumar los valores ponderados de los bits del vector $w(nT_s)$.} \\
&\text{Este número representa directamente la frecuencia inicial desde la cual se genera la señal chirp para su transmisión.} \\[1em]
&\textbf{Fórmula de codificación:} \\[1em]
&\hspace{8cm} s(nT_s) = \sum_{h=0}^{SF-1} w_h(nT_s) \cdot 2^h \\[1em]
&\text{donde:} \\
&\hspace{1cm} s(nT_s) \in \{0, ..., 2^{SF} - 1\} \text{ es el símbolo codificado} \\
&\hspace{1cm} w_h(nT_s) \in \{0, 1\} \text{ son los bits del bloque actual, ordenados desde el LSB} \\
&\hspace{1cm} SF \text{ es el Spreading Factor (cantidad de bits por símbolo)} \\
&\hspace{1cm} h \text{ es el índice del bit dentro del bloque}
\end{aligned}
$$

$$
\begin{aligned}
&\text{Suponiendo que el ancho de banda del canal utilizado es } B, \text{ lo que implica que transmitimos una muestra cada:} \\[0.5em]
&\hspace{8cm} T = \frac{1}{B} \\[1em]
&\text{Un símbolo } s(nT_s) \text{ se transmite cada:} \\[0.5em]
&\hspace{8cm} T_s = 2^{SF} \cdot T \\[1em]
&\text{Cada símbolo representa un número entero entre } 0 \text{ y } 2^{SF} - 1. \text{ Esto no solo determina la frecuencia con la que inicia el chirp,} \\
&\text{sino también cuán “extendida” estará la señal en el tiempo. A mayor } SF, \text{ mayor será la duración del símbolo y mayor la resistencia al ruido,} \\
&\text{a costa de menor tasa de transmisión.} \\[1em]
&\text{Por otro lado, el decodificador es el componente encargado de inferir el mensaje original a partir de la señal recibida.} \\
&\text{En un canal aditivo de ruido blanco gaussiano (AWGN), la estrategia óptima es la de Máxima Verosimilitud (ML).} \\
&\text{Esta consiste en proyectar la señal recibida sobre todas las señales base posibles y elegir aquella cuya proyección maximice la expresión:} \\[0.5em]
&\hspace{8cm} \max_{c} \left| \langle y, c \rangle \right| \\[1em]
&\text{Donde $c$ es una señal candidata y $y$ es la señal observada. Gracias a la ortogonalidad de las señales en FSCM,} \\
&\text{esta proyección puede implementarse eficientemente con una FFT.}
\end{aligned}
$$

$$
\begin{aligned}
&\textbf{Implementación en Python}
\end{aligned}
$$

In [3]:
import numpy as np

def bits_to_symbols(bit_array, SF):
    """
    Agrupa bits en bloques de tamaño SF y convierte cada grupo en un símbolo decimal.
    """
    if len(bit_array) % SF != 0:
        raise ValueError(f"Número de bits ({len(bit_array)}) no divisible por el SF ({SF})")

    # Convertir a array de NumPy y reorganizar en filas de SF bits
    bloques = np.array(bit_array).reshape(-1, SF)
    print (bloques)
    # Calculamos los pesos binarios desde el bit más significativo al menos
    pesos = [2**i for i in range(SF - 1, -1, -1)]

    # Multiplicamos cada grupo por los pesos y sumamos para obtener los símbolos
    symbols = []
    for grupo in bloques:
        decimal = sum(b * p for b, p in zip(grupo, pesos))
        symbols.append(decimal)

    return symbols

In [4]:



def symbols_to_bits(symbols, SF):
    """
    Convierte una lista de símbolos (números enteros) a su forma binaria, 
    usando SF bits por símbolo.
    """
    symbols = np.array(symbols)  # <- Esta línea soluciona el error

    max_val = 2**SF
    if np.any(symbols >= max_val):
        raise ValueError(f"Se encontró un símbolo mayor o igual a {max_val}, que no cabe en {SF} bits.")

    bits_acumulados = []
    for num in symbols:
        binarios = []
        for i in range(SF - 1, -1, -1):
            bit = (num >> i) & 1
            binarios.append(bit)
        bits_acumulados.extend(binarios)

    return np.array(bits_acumulados)



In [ ]:


def simulate_encoder_decoder(SF, total_bits):
    """
    Simula el proceso completo: generación de bits aleatorios,
    codificación a símbolos, decodificación y cálculo de tasa de error.
    """
    if total_bits % SF != 0:
        raise ValueError("La cantidad total de bits debe ser múltiplo del SF")

    # Paso 1: generación deL array de bits (0s y 1s) al azar
    tx_bits = np.random.randint(low=0, high=2, size=total_bits)
    
    # Paso 2: codificación (de bits a símbolos)
    tx_symbols = bits_to_symbols(tx_bits, SF)

    # Paso 3: "transmisión" sin errores (ideal), se puede modificar luego
    rx_symbols = tx_symbols.copy()

    # Paso 4: decodificación (símbolos de vuelta a bits)
    rx_bits = symbols_to_bits(rx_symbols, SF)

    # Paso 5: comparación bit a bit
    errores = np.sum(tx_bits != rx_bits)
    ber = errores / total_bits

    # Imprimir información útil para inspección manual
    print("Bits originales     (primeros 64):", tx_bits[:64])
    print("Bits reconstruidos  (primeros 64):", rx_bits[:64])
    print("-" * 50)
    print(f"Cantidad total de bits: {total_bits}")
    print(f"Errores encontrados: {errores}")
    print(f"Tasa de error (BER): {ber:.6f}")

# Configuración y ejecución de prueba
SF = 7
num_bits = SF * 1000  # Múltiplo de SF para evitar errores
simulate_encoder_decoder(SF, num_bits)


[[0 1 1 ... 1 0 0]
 [1 0 0 ... 1 1 0]
 [0 1 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 1]
 [0 0 1 ... 0 1 0]
 [1 1 1 ... 1 1 0]]
Bits originales     (primeros 64): [0 1 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 1 1 1 1 0 0 0 1 1 1 0 1
 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 1 1]
Bits reconstruidos  (primeros 64): [0 1 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 1 1 1 1 0 0 0 1 1 1 0 1
 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 1 1]
--------------------------------------------------
Cantidad total de bits: 7000
Errores encontrados: 0
Tasa de error (BER): 0.000000


$$
\begin{aligned}
&\text{El sistema emplea una técnica denominada Frequency Shift Chirp Modulation (FSCM), que codifica información binaria} \\
&\text{mediante señales tipo chirp. Cada símbolo $s(nT_s)$, representado como un número entero en el rango $\{0, 1, ..., 2^{SF}-1\}$,} \\
&\text{se transforma en una forma de onda compleja cuya frecuencia varía linealmente durante la duración del símbolo.} \\[2em]

&\textbf{1. Generación de la forma de onda (Wave-former)} \\[1em]
&\text{La señal modulada generada por el wave-former se define a partir del símbolo $s(nT_s)$, utilizando la siguiente expresión:} \\[0.5em]
&\hspace{2cm} c(nT_s + kT) = \frac{1}{\sqrt{2^{SF}}} \cdot e^{j2\pi \left[ \frac{(s(nT_s) + k)k}{2^{SF}} \right]} \\[0.5em]
&\text{donde:} \\
&\hspace{1cm} SF \text{ es el Spreading Factor, que determina la longitud del chirp y la cantidad de bits por símbolo.} \\
&\hspace{1cm} k \text{ representa el índice de la muestra dentro del símbolo.} \\
&\text{La normalización por } \frac{1}{\sqrt{2^{SF}}} \text{ asegura que todos los símbolos posean energía unitaria, condición esencial} \\[0.75em]
&\text{para la detección óptima y el análisis bajo ruido blanco aditivo (AWGN).} \\[0.75em]
&\text{Esta modulación produce chirps ortogonales para cada símbolo posible, asegurando que la proyección entre dos chirps distintos sea nula:} \\[0.75em]
&\hspace{2cm} \langle c_i, c_j \rangle = 0 \quad \text{para } i \neq j \\[0.75em]
&\text{La ortogonalidad y normalización permiten una detección robusta ante interferencias y facilitan una implementación} \\
&\text{computacionalmente eficiente del receptor.} \\[2em]

&\textbf{2. Modelo de recepción y formulación con ruido} \\[0.75em]
&\text{En presencia de ruido blanco aditivo complejo, la señal recibida por el receptor se modela como:} \\
&\hspace{2cm} r(nT_s + kT) = c(nT_s + kT) + w(nT_s + kT) \\[0.75em]
&\text{donde $w(nT_s + kT)$ representa el ruido gaussiano complejo de media cero y varianza constante.} \\
&\text{Esta formulación permite suponer sincronización ideal y símbolos equiprobables para análisis de desempeño.} \\[2em]

&\textbf{3. Detección óptima en canales AWGN} \\[0.75em]
&\text{Dado que las señales transmitidas tienen igual energía y se asume sincronización perfecta, el receptor óptimo en un canal AWGN} \\
&\text{consiste en proyectar la señal recibida sobre cada una de las formas de onda posibles $c(nT_s + kT) \mid s(nT_s) = q$, y seleccionar} \\
&\text{aquella cuya proyección tenga el módulo cuadrado máximo. Esta operación proporciona la mejor estimación del símbolo transmitido.} \\[2em]

&\textbf{4. Implementación eficiente mediante el n-Tuple Former} \\[0.75em]
&\text{Para evitar el cálculo explícito de correlaciones con cada chirp base, se propone una implementación eficiente basada en dos pasos:} \\[0.75em]
&\textbf{a. Multiplicación por el down-chirp conjugado} \\
&\text{La señal recibida se multiplica muestra a muestra por un chirp conjugado descendente:} \\[0.75em]
&\hspace{2cm} d(nT_s + kT) = r(nT_s + kT) \cdot e^{-j2\pi \frac{k^2}{2^{SF}}} \\
&\text{Esta operación elimina la componente cuadrática de frecuencia del chirp, alineando todas las posibles formas de onda en fase.} \\[0.75em]
&\textbf{b. Transformada Discreta de Fourier (FFT)} \\
&\text{Posteriormente, se aplica una Transformada Discreta de Fourier sobre el vector $d(nT_s + kT)$. El índice $p$ correspondiente al pico} \\[0.75em]
&\text{del espectro determina el símbolo detectado:} \\[0.75em]
&\hspace{2cm} \mathrm{FFT}\{d(nT_s + kT)\} \Rightarrow \max |D[p]| \Rightarrow s(nT_s) = p \\[0.75em]
&\text{A partir de las ecuaciones (11) a (16) del paper [1], esta proyección puede expresarse de forma expandida como:} \\[0.5em]
&\hspace{1.5cm} \sum_{k=0}^{2^{SF}-1} 
\underbrace{r(nT_s + kT) \cdot e^{-j2\pi \frac{k^2}{2^{SF}}}}_{\text{down-chirp: } d(nT_s + kT)}
\cdot \frac{1}{\sqrt{2^{SF}}} \cdot e^{-j2\pi \frac{p \cdot k}{2^{SF}}} \\[1em]
&\text{Este procedimiento permite identificar directamente la tupla binaria de $SF$ bits asociada al símbolo transmitido,} \\
&\text{con una complejidad computacional significativamente reducida.}
\end{aligned}